/*
 * file : sharedFunctions.h
 * Copyright (c) pfeuh <ze.pfeuh@gmail.com>
 * creation date : 2019/11/07 13:45:06
 * All rights reserved.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/********************************************/
/*                 WARNING!                 */
/*    This file is generated by yaamm.py,   */
/*  if you edit it, it will be overwritten  */
/*        by the next generation!           */
/********************************************/

// Function editCurrentSpeed is black listed.

// Function editCurrentWindowWidth is black listed.

// Function editCurrentPulsePerTurn is black listed.

// Function editCurrentClogging is black listed.

// Function editCurrentMin is black listed.

// Function editCurrentMax is black listed.

// Function editCurrentLuminosity is black listed.

// Function editCurrentDurationMin is black listed.

// Function editCurrentDurationMax is black listed.

// Function editPulsesPerRotate is black listed.

// Function editMeasurementWindow is black listed.

// Function editDirection is black listed.

// Function editMinSpeed is black listed.

// Function editMaxSpeed is black listed.

// Function editLuminosity is black listed.

// Function editDurationMin is black listed.

// Function editDurationMax is black listed.

// Function editSerialBaudrate is black listed.

// Function editSpeedSwitch is black listed.

// Function editCloggingSwitch is black listed.

// Function editVersion is black listed.

// Function editTimestamp is black listed.

// Function storeConfig is black listed.

// Function readConfig is black listed.

// Function factory is black listed.

// Function calibMin is black listed.

// Function calibMax is black listed.

